language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: b0r9ji5sKhO2ZtDwsw6gdu9d9mcMMC+w9mOsfqxVm+ZO4qX2y2q7O9lGHU6oZowDGNF+JZQZ7qyMxCC5xhydIOx3Pb+/pImsengWjtqwuncHwkH+UOVKGj4Dv4Oa6KfHE36iku6wYWoDsLNeFxpt3Q1QL/b6N0PzzZ+f3u3foEqyu6JTMTksGm//0KC5ujDkz/PEh1dUJ8WWaS6BgLqNehyBd+oEuI1VfuE2OzqZFNGRU3Dl0bKD8yQFv/G+Uv1jzCNu8aFiJ5mMlcYAmA92HHTDqn4gM+8GtRF619LX1QZpFFYfjMrXTm6FK6kERO7AzpDbqEupozkH976BZ7pdk08c/Rsg9US36xaN0pkZeNVg/AzeWq9z5qwz86WoEZNWKOhQXFFr4FMDSMMeqsHSZ+Qv3+T23WZQh6VIGbHBPyv/BvfiiAU2ebgyIVSuxiEQYrL394XJEjIP2P00sJHvYL77tRUyktag8d2CrDe5fyy090St0jPrKwpbGwb0lZwQWN+zT5P/h+1qzipb8MSVlypP7S0tJBhiug1toGjNwXnWAr5aWg4oMbxnIRFDbxEw7jnZfycExbyMLgII7RfzI2D8zS5CW5Q8OTIM/eIiSDKroJkY059kFH8yUS5dX/W2Mqtjvjk4TMDLv1IuZwuxHOLhti4Jf8ruN8/We9n/QFU=
  app: travis-restaurants
  on:
    repo: Reldalk/restaurants-app-with-travis
