language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Q6pN7N92jHIksHtvYCS0H5UqvM2EFFeq0vMy68x2nPNBJiM7P4tSl14b/Xs4GdH/4JQDy1iI67kt7iWvD+MeOXDmHyHP4WuFFuPKfz2ykKL/pE3FSG/5BGRc0ARsjIY6GideT1pQWVCJWpVyzQz4J4DZYltN9lnBPaLyCoNhexJjvU4Wk1283DnA3eeSxziGSQejaDC6GqrYVel/L5F0RwM01kGx+HNEmjg3LVKCcn5t6bvgV4ybr/XniQ1DbwTl4w081Awdgh07EYOrHx/tYTsV9L0SyoN0os1t1PFXoP3aocVlKtJdDUurRz77yyDFHuUeK7mfFS8Q/wvqYt2ruDZr/6iSjwrMPRFu+ffJIFfQSiGiN1A7o/KHLYZvY08iKxBqkIrAski9Zhm0mMWfOPv7ul1i9pTxb/5ZMIkvtEWOlcXaCkKfiiNS4u0V+xaERPC/gjlUbSrPTbm0DNwcFeRL84M7h0GL39BmHrDhM+acH8dnpj5Uhz3oXfbzpnf5U3P/t050a2RDlBxn1Wo91zEG6Ue4ar2g5vImrR5CEVPW1si1n7yaz7KDkZNHTjzVX3ff0LW/wTUKEGuFApGBfIJfNUN0l8IPX+GpNMmhsS3r5iASDGidc1D4VTI+EL4bMkO7Y3n+Eb5R7dhMP5GCUKYC42v0YX8SWioKxdR8Yzk=
  app: travis-restaurants
  on:
    repo: Reldalk/restaurants-app-with-travis
